### ISSUE TITLE
Installation procedure should offer the commands for validation of prerequisites

### ISSUE THREAD

**Issue by kamir** [pharo-iot/PharoThings#7]
Before step 5. in the setup guide we should also add the command which allows a quick test, if the "wiringPi" library is already installed as needed.

**Comment by dionisiydk** [comment]
Yes, good idea. Thank's

**Comment by oliveiraallex** [comment]
Added the WiringPi test and update commands:

https://github.com/pharo-iot/PharoThings/commit/89bca2e0635661d069bce9bf1bc563c7fdeb2863
